spring:
  datasource:
    url: jdbc:mysql://localhost:3306/transaction_db
    username: appuser
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: transaction-service

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

# JWT Configuration (must match auth-service secret)
jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437

account-service:
  url: http://127.0.0.1:8081

logging:
  level:
    com.banking.transaction: DEBUG

server:
  port: 8082